### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by tripsBro** [guillaumegenthial/streamplot#3]
**after running** : python3 testplot.py

Gtk-Message: 23:45:33.463: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "testplot.py", line 17, in <module>
    plt_mgr.update()
  File "/home/rahultripathy/.local/lib/python3.6/site-packages/streamplot.py", line 170, in update
    for name, plot in self.plots.iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

**Comment by jisus-17** [comment]
same
